# ---------------------------------------------------------------
# Serveur
# ---------------------------------------------------------------
server.port=8080

# ---------------------------------------------------------------
# Base de données PostgreSQL
# Remplace la classe DataBase.java de l'original
# ---------------------------------------------------------------
spring.datasource.url=jdbc:postgresql://dpg-d7flc31f9bms73ej7se0-a.frankfurt-postgres.render.com:5432/database_connect4
spring.datasource.username=database_connect4_user
spring.datasource.password=tET0T0RRoAkkpQ4F3W4iuEBGx0XcdTtr
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.default_schema=s01
spring.jpa.hibernate.ddl-auto=none


# ---------------------------------------------------------------
# Logs
# ---------------------------------------------------------------
logging.level.com.connect4=INFO
